### ISSUE TITLE
what is in th 'idx.cvs' and 'left lung'?

### ISSUE THREAD

**Issue by sybilWsybil** [imlab-uiip/lung-segmentation-2d#1]
I don't Know what kind of data for this code.
csv_path = '/path/to/JSRT/idx.csv'
what kind of data in idx.cvs? 
Does 'filenames' include suffix?
and what's in 'left lung' ?
left = io.imread('/path/to/JSRT/Masks/left lung/' + filename[:-4] + '.gif')
right = io.imread('/path/to/JSRT/Masks/right lung/' + filename[:-4] + '.gif')

**Comment by eclique** [comment]
@sybilWsybil, as stated in comments above, csv file should contain x-ray filenames as first column and mask filenames as second column. Example:
csv: 
```
xray_path, mask_path
JPCLN001.png, JPCLN001msk.png
...
```
`csv_path = /path/to/JSRT/idx.csv` (that will make `path` equal to /path/to/JSRT/ so  image will be loaded from /path/to/JSRT/JPCLN001.png)

Folders "left(right) lung" come with JSRT dataset (link in readme). This code merges two lung mask files into single mask.

**Comment by sybilWsybil** [comment]
@eclique, I have download the ''All247images.zip (1.33GB)'',''Nodule_Subtlety1_1 [80.9MB]'' and ''NonNodule1 [80.1MB]'' in http://www.jsrt.or.jp/jsrt-db/eng-04.php.
But there are no ''left(right) lung''. Did I do wrong?

**Comment by eclique** [comment]
@sybilWsybil Sorry, my mistake. The annotations were made as part of [this project](http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/3609/pdf/imm3609.pdf), but the [site they are referencing](http://www.isi.uu.nl/Research/Databases/SCR/) is currently down. The name of the data set is SCR (Segmentation in Chest Radiographs), maybe you can find it in some other place or the site will be functioning again.

**Comment by sybilWsybil** [comment]
@eclique  Thank you so much!

**Comment by qinriver** [comment]
I don't Know what kind of data for this code.
csv_path = '/path/to/JSRT/idx.csv'
what kind of data in idx.cvs?
do you think I should write this file by myself?
