### ISSUE TITLE
Implementing the model on Montgomery Dataset

### ISSUE THREAD

**Issue by shashankshekhardehradun** [imlab-uiip/lung-segmentation-2d#5]
Thank you for sharing the code for lung segmentation here. I am trying to implement the code for Montgomery Dataset. Do I simply change JSRT with Montgomery in order to do that? Also, there is no csv file for this dataset, do I have to create it manually?

**Comment by eclique** [comment]
Change the path to the Montgomery dataset, and change the loading function to loadDataMontgomery.
Yes, you have to create a csv file manually.

**Comment by shashankshekhardehradun** [comment]
Thanks a lot for the prompt reply! Will get back to you in case I run into problems later :p

**Comment by shashankshekhardehradun** [comment]
The JSRT Dataset contains the masked images as png files with the two masks but the Montgomery one has separate left and right mask png files, do I add them as separate entries to the csv file or do I somehow concatenate the two images into one? Thanks

**Comment by eclique** [comment]
You should create a single image with both left and right lungs.
