### ISSUE TITLE
`preprocess_JSRT.py` cannot `reshape`

### ISSUE THREAD

**Issue by sarahESL** [imlab-uiip/lung-segmentation-2d#6]
I'm guessing output of `preprocess_JSRT.py` must be used as input images for `train_model.py`. Is this correct? If yes, then on line 8, reshaping the ndarray to `(2048, 2048)` gives `ValueError: cannot reshape array of size ${size_of_ndarray} into shape (2048,2048)` on all original images from JSRT. 
Furthermore, I don't really follow why `img = 1.0 - np.fromfile(path + filename, dtype='>u2') * 1. / 4096` (changing the values like that, regardless of the reshaping) is happening as preprocessing. Could you please give a quick explanation?

**Comment by eclique** [comment]
What happens in line 8 is the following:
1. Create a numpy array from a binary file 
2. Reshape it into 2D. The images in JSRT are 2048x2048, I'm not sure why it doesn't work for you. Are you sure the files are being read at all?
3. Divide all the values by 4096 (images in JSRT are in [0, 4096] range) to scale them to [0,1].
4. Negate the result, so that 0 becomes 1, and 1 becomes 0.

**Comment by sarahESL** [comment]
Thanks for your fast response.
Well then of course something is going wrong when I run it, since doing the `1 - read_image * 1/4096` is giving negative values for me :confused:  But if it is meant for normalization, I will check the range of values on my dataset and see if the max value is different (although I am using the same JSRT dataset, so it is weird if they are different :confused: ). 
And still, if I fix the max value problem, the `np.fromfile` is reading different images to arrays that are different in size (e.g.  for image `JPCLN101.png` the array looks like `[35152 20039  3338 ... 17742 17582 16992]` with the size `794295`...and I have checked, this size is different for another image). And furthermore, none of the sizes are suitable for reshaping to (2048, 2048).

**Comment by shashankshekhardehradun** [comment]
I am facing the exact same problem. Any fix would be appreciated

**Comment by sarahESL** [comment]
@shashankshekhardehradun well since @eclique said the purpose was to normalize the values, I did a workaround myself and it worked. I used `imageio` library instead of `numpy.formfile` => ` img = imageio.imread(input_path).reshape(2048, 2048) / 255`. `255` is chosen since the image is gray scale and values are in the range of `[0, 255]`.
